baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
googleAnalitics = "G-PR8Z9SJC7F"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

  # Show reading time in minutes for posts
  showReadingTime = false

  # Show table of contents at the top of your posts (defaults to false)
  # Alternatively, add this param to post front matter for specific posts
  # toc = true

  # Show full page content in RSS feed items
  #(default is Description or Summary metadata in the front matter)
  # rssFullText = true

[languages]
  [languages.en]
    title = "Pasza's blog"
    subtitle = "a simple blog about complex things"
    keywords = ""
    copyright = "Piotr Pasza Storożenko"
    menuMore = "Show more"
    writtenBy = "Written by Piotr Pasza Storożenko"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "pasza's blog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about"
      # [[languages.en.menu.main]]
      #   identifier = "showcase"
      #   name = "Showcase"
      #   url = "/showcase"
      [[languages.en.menu.main]]
        identifier = "useful-materials"
        name = "Useful materials"
        url = "/useful-materials"